In [1]:
import torch
import torch.nn
from torch.utils.data import Dataset,DataLoader,random_split,TensorDataset

### Normal distribution

In [2]:
a=torch.randn(10,1)

In [3]:
a

tensor([[-0.5099],
        [ 0.4699],
        [ 0.7373],
        [ 0.6948],
        [-1.1969],
        [ 0.2179],
        [-1.4294],
        [ 0.7836],
        [-0.9236],
        [-1.4155]])

#### Random Integer

In [4]:
x=torch.randint(1,10,(5,2))

In [5]:
x

tensor([[4, 7],
        [9, 3],
        [4, 9],
        [4, 5],
        [8, 2]])

In [6]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [7]:
torch.linspace(1,10,5)

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

In [8]:
torch.reshape(torch.arange(1,11),(5,2))

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [9]:
torch.arange(1,11).view(2,5)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [10]:
torch.arange(1,11).view(5,-1)

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [11]:
torch.arange(1,11).view(-1,5)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

## Transpose

In [12]:
x=torch.arange(1,11).reshape(2,5)
print(f"{x}\n{x.t()}")

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
tensor([[ 1,  6],
        [ 2,  7],
        [ 3,  8],
        [ 4,  9],
        [ 5, 10]])

In [13]:
x=torch.arange(1,11).reshape(2,5)
print(x.is_contiguous())
print(x.t().is_contiguous())

True
False

In [14]:
x=torch.arange(1,11).view(2,5)
print(x.is_contiguous())
print(x.t().is_contiguous())
print(x.contiguous().view(5,2).is_contiguous())

True
False
True

## Dataset loading

In [15]:
import pandas as pd
data=pd.read_csv("https://raw.githubusercontent.com/Arannamoy/datasets/refs/heads/main/Iris%20Species/Iris.csv")
data.head(5)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [16]:
x=data.drop(columns=('Species'))
y=data['Species']

In [17]:
x.head(5)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   1            5.1           3.5            1.4           0.2
1   2            4.9           3.0            1.4           0.2
2   3            4.7           3.2            1.3           0.2
3   4            4.6           3.1            1.5           0.2
4   5            5.0           3.6            1.4           0.2

In [18]:
y.head(5)

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

In [19]:
import pandas as pd
data=pd.read_csv("https://raw.githubusercontent.com/Arannamoy/datasets/refs/heads/main/white_wine_quality.csv",sep=";")
data.head(5)
x=data.drop(columns=('quality'))
y=data['quality']
dataset=TensorDataset(torch.tensor(x.values).float(),torch.tensor(y.values).float())

In [20]:
dataset.tensors

(tensor([[ 7.0000,  0.2700,  0.3600,  ...,  3.0000,  0.4500,  8.8000],
         [ 6.3000,  0.3000,  0.3400,  ...,  3.3000,  0.4900,  9.5000],
         [ 8.1000,  0.2800,  0.4000,  ...,  3.2600,  0.4400, 10.1000],
         ...,
         [ 6.5000,  0.2400,  0.1900,  ...,  2.9900,  0.4600,  9.4000],
         [ 5.5000,  0.2900,  0.3000,  ...,  3.3400,  0.3800, 12.8000],
         [ 6.0000,  0.2100,  0.3800,  ...,  3.2600,  0.3200, 11.8000]]),
 tensor([6., 6., 6.,  ..., 6., 7., 6.]))